test_circuits/iris.py: fix https://github.com/mawatfa/ebana/issues/2
fix TypeError: OneHotEncoder.__init__() got an unexpected keyword argument sparse

`sparse` was renamed to `sparse_output` in
sklearn/preprocessing/_encoders.py